server:
  port: 18080

spring:
  application:
    name: calendar-core
  datasource:
    url: jdbc:postgresql://localhost:5432/wrongbook
    username: postgres
    password: wb
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration

app:
  snowflake:
    worker-id: 3
