server:
  port: 8084

spring:
  application:
    name: calendar-core
  datasource:
    url: jdbc:postgresql://localhost:5432/wrongbook
    username: postgres
    password: wb
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
