server:
  port: 8082

spring:
  application:
    name: wrongbook-service
  datasource:
    url: jdbc:postgresql://localhost:15432/wrongbook?stringtype=unspecified
    username: longfeng
    password: longfeng_dev
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
  flyway:
    enabled: false

app:
  snowflake:
    worker-id: 2
